name: ✨ Feature Request
about: Suggest a new idea or enhancement for PruneCopy
labels: [enhancement]
---

## Is your feature request related to a problem?
Please describe clearly what problem this feature would solve.

## Describe the solution you'd like
A clear and concise description of what you want to happen.

## Describe alternatives you've considered
Any alternative solutions or workarounds you've tried or thought of.

## Additional context
Add any other context or screenshots about the feature request here.